-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### A. Create tables
-- MAGIC
-- MAGIC Create tables to store document chunks and processed files information

-- COMMAND ----------

-- DBTITLE 1,Create table to store Document Chunks
CREATE TABLE IF NOT EXISTS insurance.rag.DocumentChunks 
(
    Id               BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    Text             STRING,    
    Source           STRING,
    PolicyName       STRING,
    UpdatedOn        TIMESTAMP
)
TBLPROPERTIES( delta.enableChangeDataFeed = true )


-- COMMAND ----------

-- DBTITLE 1,Create table to store Processed Files
CREATE TABLE IF NOT EXISTS insurance.rag.ProcessedFiles
(  
    FilePath         STRING,    
    UpdatedOn        TIMESTAMP
)
TBLPROPERTIES( delta.enableChangeDataFeed = true )
