-- =====================================================
-- Silver Layer - STORE_MASTER Dynamic Table
-- Deduplication, data quality checks, incremental refresh
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.SILVER.STORE_MASTER
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Silver layer store master with deduplication and quality validation'
AS
SELECT
    STORE_CODE,
    STORE_NAME,
    COUNTRY_CODE,
    REGION_CODE,
    TAX_JURISDICTION_CODE,
    FORMAT_CODE,
    CITY,
    STATE_CODE,
    POSTAL_CODE,
    ADDRESS_LINE1,
    LATITUDE,
    LONGITUDE,
    STORE_OPEN_DATE,
    STORE_CLOSE_DATE,
    LIFECYCLE_STATUS,
    FLOOR_AREA_SQFT,
    ANNUAL_RENT_USD,
    IS_ACTIVE,
    EFFECTIVE_START_DATE,
    EFFECTIVE_END_DATE,
    
    -- Data Quality Flag
    CASE 
        WHEN STORE_CODE IS NULL THEN FALSE
        WHEN STORE_NAME IS NULL OR TRIM(STORE_NAME) = '' THEN FALSE
        WHEN COUNTRY_CODE IS NULL THEN FALSE
        WHEN IS_ACTIVE NOT IN ('Y', 'N') THEN FALSE
        WHEN LATITUDE < -90 OR LATITUDE > 90 THEN FALSE
        WHEN LONGITUDE < -180 OR LONGITUDE > 180 THEN FALSE
        WHEN STORE_CLOSE_DATE IS NOT NULL AND STORE_CLOSE_DATE < STORE_OPEN_DATE THEN FALSE
        WHEN EFFECTIVE_END_DATE < EFFECTIVE_START_DATE THEN FALSE
        WHEN FLOOR_AREA_SQFT < 0 THEN FALSE
        WHEN ANNUAL_RENT_USD < 0 THEN FALSE
        ELSE TRUE
    END AS IS_VALID_RECORD,
    
    -- Audit Columns
    __FILE_NAME,
    __ROW_NUMBER AS __SOURCE_ROW_NUMBER,
    __LOAD_TS AS __BRONZE_LOAD_TS

FROM SALES_DEV.BRONZE.STORE_MASTER

-- Deduplication: Keep latest record per STORE_CODE
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_CODE 
    ORDER BY __LOAD_TS DESC, __ROW_NUMBER DESC
) = 1;
