-- =====================================================
-- Gold Layer - Product Dimension & Bridge Table
-- DIM_PRODUCT: Full hierarchy Category > Family > Model > SKU
-- BRIDGE_PRODUCT_COUNTRY: Many-to-many product-country availability
-- =====================================================

-- =====================================================
-- DIM_PRODUCT - Main Product Dimension
-- Grain: SKU level with denormalized hierarchy
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Product dimension with full hierarchy: Category > Family > Model > SKU for product analytics'
AS
SELECT
    -- Surrogate Key (Hash-based for fact joins)
    SHA2(CONCAT(
        COALESCE(s.SKU_CODE, ''),
        COALESCE(TO_VARCHAR(s.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS PRODUCT_DIM_KEY,
    
    -- SKU Level (Grain)
    s.SKU_CODE,
    s.VARIANT,
    s.PRICE_TIER,
    s.GLOBAL_LAUNCH_DATE AS SKU_LAUNCH_DATE,
    s.IS_ACTIVE AS SKU_IS_ACTIVE,
    
    -- Model Level
    m.MODEL_CODE,
    m.MODEL_NAME,
    m.LAUNCH_DATE AS MODEL_LAUNCH_DATE,
    m.DISCONTINUE_DATE AS MODEL_DISCONTINUE_DATE,
    m.LIFECYCLE_STATUS,
    
    -- Family Level
    f.FAMILY_CODE,
    f.FAMILY_NAME,
    f.LAUNCH_YEAR AS FAMILY_LAUNCH_YEAR,
    
    -- Category Level
    c.CATEGORY_CODE,
    c.CATEGORY_NAME,
    c.REPORTING_SEGMENT,
    
    -- SCD Type 2 Columns
    s.__BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    s.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.PRODUCT_SKU_MASTER s
JOIN SALES_DEV.SILVER.PRODUCT_MODEL_MASTER m 
    ON s.MODEL_CODE = m.MODEL_CODE AND m.IS_VALID_RECORD = TRUE
JOIN SALES_DEV.SILVER.PRODUCT_FAMILY_MASTER f 
    ON m.FAMILY_CODE = f.FAMILY_CODE AND f.IS_VALID_RECORD = TRUE
JOIN SALES_DEV.SILVER.PRODUCT_CATEGORY_MASTER c 
    ON f.CATEGORY_CODE = c.CATEGORY_CODE AND c.IS_VALID_RECORD = TRUE
WHERE s.IS_VALID_RECORD = TRUE;

-- Column Comments for DIM_PRODUCT
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN PRODUCT_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN SKU_CODE COMMENT 'Stock keeping unit code - lowest grain';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN VARIANT COMMENT 'SKU variant description (storage/color)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN PRICE_TIER COMMENT 'Pricing tier: Standard/Premium';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN SKU_LAUNCH_DATE COMMENT 'Global SKU launch date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN SKU_IS_ACTIVE COMMENT 'SKU active status flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_CODE COMMENT 'Product model identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_NAME COMMENT 'Product model display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_LAUNCH_DATE COMMENT 'Model global launch date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN MODEL_DISCONTINUE_DATE COMMENT 'Model discontinuation date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN LIFECYCLE_STATUS COMMENT 'Product lifecycle stage: ACTIVE/DISCONTINUED';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN FAMILY_CODE COMMENT 'Product family identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN FAMILY_NAME COMMENT 'Product family display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN FAMILY_LAUNCH_YEAR COMMENT 'Year product family was launched';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN CATEGORY_CODE COMMENT 'Product category identifier';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN CATEGORY_NAME COMMENT 'Product category display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN REPORTING_SEGMENT COMMENT 'Financial reporting segment';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_PRODUCT ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';

-- =====================================================
-- BRIDGE_PRODUCT_COUNTRY - Many-to-Many Bridge Table
-- Links products to countries where they are available
-- Prevents row explosion in DIM_PRODUCT
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Bridge table linking products to countries where they are available - many-to-many relationship'
AS
SELECT
    -- Composite Key
    SHA2(CONCAT(
        COALESCE(pa.SKU_CODE, ''),
        COALESCE(pa.COUNTRY_CODE, ''),
        COALESCE(TO_VARCHAR(pa.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS BRIDGE_KEY,
    
    -- Foreign Keys (for joining to dimensions)
    SHA2(CONCAT(
        COALESCE(pa.SKU_CODE, ''),
        COALESCE(TO_VARCHAR(ps.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS PRODUCT_DIM_KEY,
    
    SHA2(CONCAT(
        COALESCE(pa.COUNTRY_CODE, ''),
        COALESCE(TO_VARCHAR(cm.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS COUNTRY_DIM_KEY,
    
    -- Business Keys
    pa.SKU_CODE,
    pa.COUNTRY_CODE,
    
    -- Availability Attributes
    pa.LOCAL_LAUNCH_DATE,
    pa.LOCAL_DISCONTINUE_DATE,
    pa.IS_AVAILABLE,
    
    -- Audit
    pa.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.PRODUCT_COUNTRY_AVAILABILITY pa
JOIN SALES_DEV.SILVER.PRODUCT_SKU_MASTER ps 
    ON pa.SKU_CODE = ps.SKU_CODE AND ps.IS_VALID_RECORD = TRUE
JOIN SALES_DEV.SILVER.COUNTRY_MASTER cm 
    ON pa.COUNTRY_CODE = cm.COUNTRY_CODE AND cm.IS_VALID_RECORD = TRUE
WHERE pa.IS_VALID_RECORD = TRUE;

-- Column Comments for BRIDGE_PRODUCT_COUNTRY
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN BRIDGE_KEY COMMENT 'Unique bridge record key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN PRODUCT_DIM_KEY COMMENT 'Foreign key to DIM_PRODUCT';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN COUNTRY_DIM_KEY COMMENT 'Foreign key to DIM_COUNTRY';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN SKU_CODE COMMENT 'Product SKU business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN COUNTRY_CODE COMMENT 'Country business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN LOCAL_LAUNCH_DATE COMMENT 'Country-specific product launch date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN LOCAL_DISCONTINUE_DATE COMMENT 'Country-specific discontinuation date';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.BRIDGE_PRODUCT_COUNTRY ALTER COLUMN IS_AVAILABLE COMMENT 'Product availability flag in country';
