-- =====================================================
-- Task DAG to Automate Bronze Layer Data Loading
-- Root task with sub-tasks for each table load
-- =====================================================

-- Root Task (Parent) - Controls the DAG schedule
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    COMMENT = 'Root task to orchestrate bronze layer data loading'
AS
    SELECT 'Bronze data load initiated at ' || CURRENT_TIMESTAMP();

-- Sub-Task 1: Load REGION_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_REGION_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.REGION_MASTER
    FROM (
        SELECT 
            $1, $2, $3, $4, $5, $6, $7,
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER,
            CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/country-master/.*region_master.*\.csv';

-- Sub-Task 2: Load CURRENCY_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_CURRENCY_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.CURRENCY_MASTER
    FROM (
        SELECT 
            $1, $2, $3, $4, $5, $6, $7, $8, $9,
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER,
            CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/country-master/.*currency_master.*\.csv';

-- Sub-Task 3: Load TAX_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_TAX_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.TAX_MASTER
    FROM (
        SELECT 
            $1, $2, $3, $4, $5, $6, $7, $8, $9,
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER,
            CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/country-master/.*tax_master.*\.csv';

-- Sub-Task 4: Load COUNTRY_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_COUNTRY_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.COUNTRY_MASTER
    FROM (
        SELECT 
            $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER,
            CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/country-master/.*country_master.*\.csv';

-- Sub-Task 5: Load PRODUCT_CATEGORY_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_PRODUCT_CATEGORY_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.PRODUCT_CATEGORY_MASTER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/product-master/.*product_category_master.*\.csv';

-- Sub-Task 6: Load PRODUCT_FAMILY_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_PRODUCT_FAMILY_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.PRODUCT_FAMILY_MASTER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/product-master/.*product_family_master.*\.csv';

-- Sub-Task 7: Load PRODUCT_MODEL_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_PRODUCT_MODEL_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.PRODUCT_MODEL_MASTER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/product-master/.*product_model_master.*\.csv';

-- Sub-Task 8: Load PRODUCT_SKU_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_PRODUCT_SKU_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.PRODUCT_SKU_MASTER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/product-master/.*product_sku_master.*\.csv';

-- Sub-Task 9: Load PRODUCT_COUNTRY_AVAILABILITY
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_PRODUCT_COUNTRY_AVAILABILITY_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.PRODUCT_COUNTRY_AVAILABILITY
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/product-master/.*product_country_availability.*\.csv';

-- Sub-Task 10: Load STORE_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_STORE_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.STORE_MASTER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/store-master/.*store_master.*\.csv';

-- Sub-Task 11: Load CUSTOMER_MASTER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_CUSTOMER_MASTER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.CUSTOMER_MASTER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/customer-master/.*customer_master.*\.csv';

-- Sub-Task 12: Load SALES_HEADER
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_SALES_HEADER_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.SALES_HEADER
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/sales-transaction/.*sales_header.*\.csv';

-- Sub-Task 13: Load SALES_ITEM
CREATE OR REPLACE TASK SALES_DEV.BRONZE.LOAD_SALES_ITEM_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK
AS
    COPY INTO SALES_DEV.BRONZE.SALES_ITEM
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,
            METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, CURRENT_TIMESTAMP()
        FROM @SALES_DEV.BRONZE.SALES_ANALYTICS_STAGE/
    )
    FILE_FORMAT = SALES_DEV.COMMON.CSV_FORMAT
    PATTERN = '.*/sales-transaction/.*sales_item.*\.csv';

-- =====================================================
-- Resume all tasks (starting from child tasks, then root)
-- =====================================================
ALTER TASK SALES_DEV.BRONZE.LOAD_REGION_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_CURRENCY_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_TAX_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_COUNTRY_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_PRODUCT_CATEGORY_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_PRODUCT_FAMILY_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_PRODUCT_MODEL_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_PRODUCT_SKU_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_PRODUCT_COUNTRY_AVAILABILITY_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_STORE_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_CUSTOMER_MASTER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_SALES_HEADER_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_SALES_ITEM_TASK RESUME;
ALTER TASK SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK RESUME;

-- =====================================================
-- Execute the root task manually (optional)
-- =====================================================
-- EXECUTE TASK SALES_DEV.BRONZE.LOAD_BRONZE_ROOT_TASK;

-- =====================================================
-- View task DAG structure
-- =====================================================
-- SHOW TASKS IN SCHEMA SALES_DEV.BRONZE;
