-- =====================================================
-- Gold Layer - DIM_STORE (SCD Type 2)
-- Store dimension with location and operational attributes
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Store dimension with location and operational attributes for retail analytics'
AS
SELECT
    -- Surrogate Key (Hash-based for fact joins)
    SHA2(CONCAT(
        COALESCE(STORE_CODE, ''),
        COALESCE(TO_VARCHAR(__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS STORE_DIM_KEY,
    
    -- Business Key
    STORE_CODE,
    
    -- Store Attributes
    STORE_NAME,
    FORMAT_CODE,
    LIFECYCLE_STATUS,
    
    -- Location Attributes
    COUNTRY_CODE,
    REGION_CODE,
    STATE_CODE,
    CITY,
    POSTAL_CODE,
    ADDRESS_LINE1,
    LATITUDE,
    LONGITUDE,
    
    -- Tax & Operations
    TAX_JURISDICTION_CODE,
    FLOOR_AREA_SQFT,
    ANNUAL_RENT_USD,
    
    -- Status & Dates
    STORE_OPEN_DATE,
    STORE_CLOSE_DATE,
    IS_ACTIVE,
    
    -- SCD Type 2 Columns
    __BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    __BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.STORE_MASTER
WHERE IS_VALID_RECORD = TRUE;

-- =====================================================
-- Column Comments for Semantic Layer
-- =====================================================
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_CODE COMMENT 'Unique store identifier - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_NAME COMMENT 'Store display name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN FORMAT_CODE COMMENT 'Store format type: MALL/MINI/FLAGSHIP';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN LIFECYCLE_STATUS COMMENT 'Store operational status: ACTIVE/CLOSED';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN COUNTRY_CODE COMMENT 'Country where store is located';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN REGION_CODE COMMENT 'Geographic region code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STATE_CODE COMMENT 'State or province code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN CITY COMMENT 'City name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN POSTAL_CODE COMMENT 'Postal or ZIP code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN ADDRESS_LINE1 COMMENT 'Street address';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN LATITUDE COMMENT 'Geographic latitude for mapping';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN LONGITUDE COMMENT 'Geographic longitude for mapping';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN TAX_JURISDICTION_CODE COMMENT 'Tax jurisdiction for store location';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN FLOOR_AREA_SQFT COMMENT 'Store floor area in square feet';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN ANNUAL_RENT_USD COMMENT 'Annual rent amount in USD';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_OPEN_DATE COMMENT 'Date store opened';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN STORE_CLOSE_DATE COMMENT 'Date store closed (if applicable)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN IS_ACTIVE COMMENT 'Store active status flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_STORE ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';
