-- =====================================================
-- Gold Layer - DIM_CUSTOMER (SCD Type 2)
-- Customer dimension with demographics and loyalty attributes
-- =====================================================

CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = INCREMENTAL
    INITIALIZE = ON_CREATE
    COMMENT = 'Customer dimension with demographics and loyalty attributes for customer analytics'
AS
SELECT
    -- Surrogate Key (Hash-based for fact joins)
    SHA2(CONCAT(
        COALESCE(CUSTOMER_ID, ''),
        COALESCE(TO_VARCHAR(__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS CUSTOMER_DIM_KEY,
    
    -- Business Keys
    CUSTOMER_ID,
    CUSTOMER_NUMBER,
    
    -- Customer Name
    FIRST_NAME,
    LAST_NAME,
    FULL_NAME,
    
    -- Demographics
    GENDER,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE_NUMBER,
    
    -- Address
    STREET_ADDRESS,
    CITY,
    STATE_PROVINCE,
    POSTAL_CODE,
    COUNTRY_CODE,
    COUNTRY_NAME,
    REGION,
    
    -- Preferences & Segmentation
    PREFERRED_LANGUAGE,
    CUSTOMER_SEGMENT,
    LOYALTY_TIER,
    
    -- Status
    REGISTRATION_DATE,
    IS_ACTIVE,
    SOURCE_SYSTEM,
    RECORD_SOURCE,
    
    -- SCD Type 2 Columns
    __BRONZE_LOAD_TS AS EFFECTIVE_START_TS,
    CAST('9999-12-31 23:59:59' AS TIMESTAMP_NTZ) AS EFFECTIVE_END_TS,
    TRUE AS IS_CURRENT,
    
    -- Audit
    __BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.CUSTOMER_MASTER
WHERE IS_VALID_RECORD = TRUE;

-- =====================================================
-- Column Comments for Semantic Layer
-- =====================================================
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_DIM_KEY COMMENT 'Hash-based surrogate key for fact table joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_ID COMMENT 'Unique customer UUID - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_NUMBER COMMENT 'Business customer reference number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN FIRST_NAME COMMENT 'Customer first name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN LAST_NAME COMMENT 'Customer last name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN FULL_NAME COMMENT 'Customer full name for display';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN GENDER COMMENT 'Customer gender';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN DATE_OF_BIRTH COMMENT 'Customer date of birth';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN EMAIL COMMENT 'Customer email address';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN PHONE_NUMBER COMMENT 'Customer phone number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN STREET_ADDRESS COMMENT 'Customer street address';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CITY COMMENT 'Customer city';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN STATE_PROVINCE COMMENT 'Customer state or province';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN POSTAL_CODE COMMENT 'Customer postal code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN COUNTRY_CODE COMMENT 'Customer country code';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN COUNTRY_NAME COMMENT 'Customer country name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN REGION COMMENT 'Geographic region';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN PREFERRED_LANGUAGE COMMENT 'Customer preferred language';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN CUSTOMER_SEGMENT COMMENT 'Customer segment: Consumer/Business';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN LOYALTY_TIER COMMENT 'Loyalty program tier: None/Silver/Gold/Platinum';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN REGISTRATION_DATE COMMENT 'Date customer registered';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN IS_ACTIVE COMMENT 'Customer active status';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN EFFECTIVE_START_TS COMMENT 'SCD2 record effective start';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN EFFECTIVE_END_TS COMMENT 'SCD2 record effective end';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_CUSTOMER ALTER COLUMN IS_CURRENT COMMENT 'SCD2 current record indicator';
