-- =====================================================
-- Gold Layer - DIM_DATE & FACT_SALES
-- All dynamic tables for full lineage support
-- =====================================================

-- =====================================================
-- DIM_DATE - Calendar Dimension (Dynamic Table)
-- Derived from SILVER.SALES_HEADER date range
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Date dimension derived from sales transaction date range for time-based analytics'
AS
SELECT DISTINCT
    SHA2(TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYYMMDD'), 256) AS DATE_DIM_KEY,
    TRANSACTION_TIMESTAMP AS DATE_KEY,
    YEAR(TRANSACTION_TIMESTAMP) AS YEAR_NUMBER,
    QUARTER(TRANSACTION_TIMESTAMP) AS QUARTER_NUMBER,
    MONTH(TRANSACTION_TIMESTAMP) AS MONTH_NUMBER,
    WEEKOFYEAR(TRANSACTION_TIMESTAMP) AS WEEK_NUMBER,
    DAYOFYEAR(TRANSACTION_TIMESTAMP) AS DAY_OF_YEAR,
    DAYOFMONTH(TRANSACTION_TIMESTAMP) AS DAY_OF_MONTH,
    DAYOFWEEK(TRANSACTION_TIMESTAMP) AS DAY_OF_WEEK,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYY') AS YEAR_NAME,
    'Q' || QUARTER(TRANSACTION_TIMESTAMP) AS QUARTER_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'MMMM') AS MONTH_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'MON') AS MONTH_SHORT_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'DY') AS DAY_NAME,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYY-MM') AS YEAR_MONTH,
    TO_VARCHAR(TRANSACTION_TIMESTAMP, 'YYYY') || '-Q' || QUARTER(TRANSACTION_TIMESTAMP) AS YEAR_QUARTER,
    CASE WHEN MONTH(TRANSACTION_TIMESTAMP) >= 4 THEN YEAR(TRANSACTION_TIMESTAMP) ELSE YEAR(TRANSACTION_TIMESTAMP) - 1 END AS FISCAL_YEAR,
    CASE WHEN MONTH(TRANSACTION_TIMESTAMP) >= 4 THEN QUARTER(TRANSACTION_TIMESTAMP) - 1 ELSE QUARTER(TRANSACTION_TIMESTAMP) + 3 END AS FISCAL_QUARTER,
    CASE WHEN DAYOFWEEK(TRANSACTION_TIMESTAMP) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY
FROM SALES_DEV.SILVER.SALES_HEADER
WHERE IS_VALID_RECORD = TRUE;

-- Column Comments for DIM_DATE
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DATE_DIM_KEY COMMENT 'Hash-based surrogate key for fact joins';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DATE_KEY COMMENT 'Calendar date - business key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_NUMBER COMMENT 'Calendar year number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN QUARTER_NUMBER COMMENT 'Calendar quarter (1-4)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN MONTH_NUMBER COMMENT 'Calendar month (1-12)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN WEEK_NUMBER COMMENT 'Week of year (1-53)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_OF_YEAR COMMENT 'Day of year (1-366)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_OF_MONTH COMMENT 'Day of month (1-31)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_OF_WEEK COMMENT 'Day of week (0=Sun, 6=Sat)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_NAME COMMENT 'Year as string';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN QUARTER_NAME COMMENT 'Quarter name (Q1-Q4)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN MONTH_NAME COMMENT 'Full month name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN MONTH_SHORT_NAME COMMENT 'Abbreviated month name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN DAY_NAME COMMENT 'Abbreviated day name';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_MONTH COMMENT 'Year-Month (YYYY-MM)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN YEAR_QUARTER COMMENT 'Year-Quarter (YYYY-QN)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN FISCAL_YEAR COMMENT 'Fiscal year (Apr-Mar)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN FISCAL_QUARTER COMMENT 'Fiscal quarter (1-4)';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN IS_WEEKEND COMMENT 'Weekend flag';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.DIM_DATE ALTER COLUMN IS_HOLIDAY COMMENT 'Holiday flag';

-- =====================================================
-- FACT_SALES_HEADER - Transaction Level Fact
-- Grain: One row per transaction
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Sales header fact at transaction grain for transaction-level analytics'
AS
SELECT
    -- Fact Key
    SHA2(CONCAT(
        COALESCE(sh.TRANSACTION_ID, ''),
        COALESCE(TO_VARCHAR(sh.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS FACT_SALES_HEADER_KEY,
    
    -- Dimension Keys from Gold Layer
    c.CUSTOMER_DIM_KEY,
    s.STORE_DIM_KEY,
    cn.COUNTRY_DIM_KEY,
    d.DATE_DIM_KEY,
    
    -- Degenerate Dimensions
    sh.TRANSACTION_ID,
    sh.TRANSACTION_NUMBER,
    
    -- Transaction Attributes
    sh.TRANSACTION_TIMESTAMP,
    sh.CHANNEL_ID,
    sh.PAYMENT_METHOD,
    sh.CURRENCY,
    
    -- Measures (Additive Facts)
    sh.GROSS_AMOUNT,
    sh.TOTAL_DISCOUNT,
    sh.TOTAL_TAX,
    sh.NET_TOTAL,
    
    -- Count Measure
    1 AS TRANSACTION_COUNT,
    
    -- Audit
    sh.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.SALES_HEADER sh
JOIN SALES_DEV.GOLD.DIM_CUSTOMER c 
    ON sh.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
JOIN SALES_DEV.GOLD.DIM_STORE s 
    ON sh.STORE_ID = s.STORE_CODE AND s.IS_CURRENT = TRUE
JOIN SALES_DEV.GOLD.DIM_COUNTRY cn 
    ON s.COUNTRY_CODE = cn.COUNTRY_CODE AND cn.IS_CURRENT = TRUE
JOIN SALES_DEV.GOLD.DIM_DATE d 
    ON sh.TRANSACTION_TIMESTAMP = d.DATE_KEY
WHERE sh.IS_VALID_RECORD = TRUE;

-- Column Comments for FACT_SALES_HEADER
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN FACT_SALES_HEADER_KEY COMMENT 'Unique transaction fact key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN CUSTOMER_DIM_KEY COMMENT 'Foreign key to DIM_CUSTOMER';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN STORE_DIM_KEY COMMENT 'Foreign key to DIM_STORE';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN COUNTRY_DIM_KEY COMMENT 'Foreign key to DIM_COUNTRY';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN DATE_DIM_KEY COMMENT 'Foreign key to DIM_DATE';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TRANSACTION_ID COMMENT 'Transaction UUID - degenerate dimension';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TRANSACTION_NUMBER COMMENT 'Transaction reference number';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN CHANNEL_ID COMMENT 'Sales channel: POS/WEB';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN PAYMENT_METHOD COMMENT 'Payment method used';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN GROSS_AMOUNT COMMENT 'Total before discounts - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TOTAL_DISCOUNT COMMENT 'Total discount - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TOTAL_TAX COMMENT 'Total tax - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN NET_TOTAL COMMENT 'Final amount - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_HEADER ALTER COLUMN TRANSACTION_COUNT COMMENT 'Count measure for aggregations';

-- =====================================================
-- FACT_SALES_ITEM - Line Item Level Fact
-- Grain: One row per line item
-- References FACT_SALES_HEADER for header context
-- =====================================================
CREATE OR REPLACE DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
    COMMENT = 'Sales item fact at line item grain for product-level analytics'
AS
SELECT
    -- Fact Key
    SHA2(CONCAT(
        COALESCE(si.TRANSACTION_LINE_ID, ''),
        COALESCE(TO_VARCHAR(si.__BRONZE_LOAD_TS, 'YYYY-MM-DD HH24:MI:SS.FF6'), '')
    ), 256) AS FACT_SALES_ITEM_KEY,
    
    -- Parent Fact Key
    fh.FACT_SALES_HEADER_KEY,
    
    -- Dimension Keys (inherited from header + product)
    fh.CUSTOMER_DIM_KEY,
    p.PRODUCT_DIM_KEY,
    fh.STORE_DIM_KEY,
    fh.COUNTRY_DIM_KEY,
    fh.DATE_DIM_KEY,
    
    -- Degenerate Dimensions
    si.TRANSACTION_LINE_ID,
    fh.TRANSACTION_ID,
    fh.TRANSACTION_NUMBER,
    
    -- Transaction Attributes (from header)
    fh.TRANSACTION_TIMESTAMP,
    fh.CHANNEL_ID,
    fh.CURRENCY,
    
    -- Measures (Additive Facts)
    si.QUANTITY,
    si.UNIT_PRICE,
    si.DISCOUNT_AMOUNT,
    si.TAX_AMOUNT,
    si.LINE_TOTAL,
    
    -- Count Measure
    1 AS LINE_COUNT,
    
    -- Audit
    si.__BRONZE_LOAD_TS AS __SOURCE_LOAD_TS

FROM SALES_DEV.SILVER.SALES_ITEM si
JOIN SALES_DEV.GOLD.FACT_SALES_HEADER fh 
    ON si.TRANSACTION_ID = fh.TRANSACTION_ID
JOIN SALES_DEV.GOLD.DIM_PRODUCT p 
    ON si.SKU_CODE = p.SKU_CODE AND p.IS_CURRENT = TRUE
WHERE si.IS_VALID_RECORD = TRUE;

-- Column Comments for FACT_SALES_ITEM
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN FACT_SALES_ITEM_KEY COMMENT 'Unique line item fact key';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN FACT_SALES_HEADER_KEY COMMENT 'Foreign key to FACT_SALES_HEADER';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN PRODUCT_DIM_KEY COMMENT 'Foreign key to DIM_PRODUCT';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN TRANSACTION_LINE_ID COMMENT 'Line item identifier - grain';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN QUANTITY COMMENT 'Quantity sold - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN UNIT_PRICE COMMENT 'Price per unit';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN DISCOUNT_AMOUNT COMMENT 'Line discount - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN TAX_AMOUNT COMMENT 'Line tax - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN LINE_TOTAL COMMENT 'Line total - additive measure';
ALTER DYNAMIC TABLE SALES_DEV.GOLD.FACT_SALES_ITEM ALTER COLUMN LINE_COUNT COMMENT 'Count measure for line items';
